#pragma once

//---------------------------------------------------------------------------
#include "DSC_Config.hpp"

//---------------------------------------------------------------------------

#ifndef _APPLICATION_UI_H_
#define _APPLICATION_UI_H_

//---------------------------------------------------------------------------

#define APP_PREVIOUS_MENU_CHAR										','
#define APP_MAIN_MENU_CHAR											'M'
#define APP_QUIT_CHAR												'Q'

#define APP_MAIN_MENU												1
#define APP_SYSTEM_MANAGER_CHAR										'0'
#define APP_PARTITION_MANAGER_CHAR									'1'
#define APP_SPECIFIC_FUNCTIONS_CHAR                                 '2'
#define APP_READ_SYSTEM_INFORMATION_CHAR                            '3'
#define APP_READ_SYSTEM_CAPABILITIES_CHAR                           '4'
#define APP_READ_TROUBLE_INFORMATION_CHAR                           '5'

#define APP_SYSTEM_MANAGER_MENU										2
#define APP_SYSTEM_MANAGER_REFRESH_CHAR                             '0'
#define APP_SYSTEM_MANAGER_GET_TROUBLE_STATUS_CHAR					'1'
#define APP_SYSTEM_MANAGER_READ_SYSTEM_DATE_TIME_CHAR				'2'
#define APP_SYSTEM_MANAGER_WRITE_SYSTEM_DATE_TIME_CHAR				'3'
#define APP_SYSTEM_MANAGER_GET_VIRTUAL_ZONE_MANAGER_CHAR			'4'
#define APP_SYSTEM_MANAGER_READ_ACCESS_CODE_ASSIGNMENTS_CHAR        '5'
#define APP_SYSTEM_MANAGER_ADD_ACCESS_CODE_ASSIGNMENTS_CHAR         '6'
#define APP_SYSTEM_MANAGER_REMOVE_ACCESS_CODE_ASSIGNMENTS_CHAR      '7'
#define APP_SYSTEM_MANAGER_VIRTUAL_KEYPAD_MANAGER_CHAR              '8'
#define APP_SYSTEM_MANAGER_GET_ALARM_TYPES_CHAR                     '9'

#define APP_VIRTUAL_ZONE_MANAGER_MENU								3
#define APP_VIRTUAL_ZONE_MANAGER_REFRESH_CHAR						'0'
#define APP_VIRTUAL_ZONE_MANAGER_GET_NUMBER_OF_VIRTUAL_ZONES_CHAR	'1'
#define APP_VIRTUAL_ZONE_MANAGER_GET_VIRTUAL_ZONE_CHAR				'2'

#define APP_VIRTUAL_ZONE_MENU										4
#define APP_VIRTUAL_ZONE_REFRESH_CHAR								'0'
#define APP_VIRTUAL_ZONE_GET_ZONE_NUMBER_CHAR						'1'
#define APP_VIRTUAL_ZONE_GET_SYSTEMINDEX_CHAR						'2'
#define APP_VIRTUAL_ZONE_GET_VIRTUAL_ZONE_STATUS_CHAR				'3'

#define APP_VIRTUAL_ZONE_STATUS_MENU                                5
#define APP_VIRTUAL_ZONE_STATUS_REFRESH_CHAR                        '0'
#define APP_VIRTUAL_ZONE_STATUS_GET_SYSTEMINDEX_CHAR                '1'
#define APP_VIRTUAL_ZONE_STATUS_WRITE_CHAR                          '2'
#define APP_VIRTUAL_ZONE_STATUS_GET_OPEN_CHAR                       '3'
#define APP_VIRTUAL_ZONE_STATUS_GET_TAMPER_CHAR                     '4'
#define APP_VIRTUAL_ZONE_STATUS_GET_FAULT_CHAR                      '5'
#define APP_VIRTUAL_ZONE_STATUS_GET_LOW_BATTERY_CHAR                '6'
#define APP_VIRTUAL_ZONE_STATUS_GET_AC_TROUBLE_CHAR                 '7'
#define APP_VIRTUAL_ZONE_STATUS_GET_MASKED_CHAR                     '8'
#define APP_VIRTUAL_ZONE_STATUS_SET_OPEN_CHAR                       '9'
#define APP_VIRTUAL_ZONE_STATUS_SET_TAMPER_CHAR                     'A'
#define APP_VIRTUAL_ZONE_STATUS_SET_FAULT_CHAR                      'B'
#define APP_VIRTUAL_ZONE_STATUS_SET_LOW_BATTERY_CHAR                'C'
#define APP_VIRTUAL_ZONE_STATUS_SET_AC_TROUBLE_CHAR                 'D'
#define APP_VIRTUAL_ZONE_STATUS_SET_MASKED_CHAR                     'E'

#define APP_PARTITION_MANAGER_MENU									6
#define APP_PARTITION_MANAGER_REFRESH_CHAR							'0'
#define APP_PARTITION_MANAGER_GET_NUMBER_OF_PARTITIONS_CHAR			'1'
#define APP_PARTITION_MANAGER_GET_PARTITION_CHAR					'2'

#define APP_PARTITION_MENU											7
#define APP_PARTITION_REFRESH_CHAR									'0'
#define APP_PARTITION_GET_LABEL_CHAR								'1'
#define APP_PARTITION_GET_ENABLED_CHAR								'2'
#define APP_PARTITION_GET_SYSTEMINDEX_CHAR							'3'
#define APP_PARTITION_GET_PARTITION_STATE_DATA_CHAR					'4'
#define APP_PARTITION_WRITE_PARTITION_LABEL_CHAR					'5'
#define APP_PARTITION_ARM_PARTITION_WITH_ACCESS_CREDENTIALS_CHAR	'6'
#define APP_PARTITION_DISARM_PARTITION_WITH_ACCESS_CREDENTIALS_CHAR	'7'
#define APP_PARTITION_GET_ZONE_MANAGER_CHAR							'8'
#define APP_PARTITION_GET_ACCESSCODE_MANAGER_CHAR					'9'
#define APP_PARTITION_SILENCE_TROUBLE_BEEPS_CHAR                    'A'
#define APP_PARTITION_ACTIVATE_FAP_FIRE_CHAR						'B'
#define APP_PARTITION_ACTIVATE_FAP_AUX_CHAR							'C'
#define APP_PARTITION_ACTIVATE_FAP_PANIC_CHAR						'D'
#define APP_PARTITION_WRITE_DOOR_CHIME_STATE_CHAR					'E'
#define APP_PARTITION_GET_DOOR_CHIME_STATE_CHAR						'F'
#define APP_PARTITION_ACTIVATE_COMMAND_OUTPUT_CHAR					'G'
#define APP_PARTITION_GET_ALARM_TYPES_CHAR                          'H'

#define APP_ZONE_MANAGER_MENU										8
#define APP_ZONE_MANAGER_REFRESH_CHAR								'0'
#define APP_ZONE_MANAGER_GET_NUMBER_OF_ZONES_CHAR					'1'
#define APP_ZONE_MANAGER_GET_ZONE_CHAR								'2'

#define APP_ACCESSCODE_MANAGER_MENU									9
#define APP_ACCESSCODE_MANAGER_REFRESH_CHAR							'0'
#define APP_ACCESSCODE_MANAGER_GET_NUMBER_OF_ACESSS_CODES_CHAR		'1'
#define APP_ACCESSCODE_MANAGER_GET_ACCESS_CODE_CHAR					'2'

#define APP_ZONE_MENU												10
#define APP_ZONE_REFRESH_CHAR										'0'
#define APP_ZONE_GET_LABEL_CHAR										'1'
#define APP_ZONE_GET_SYSTEM_INDEX_CHAR								'2'
#define APP_ZONE_GET_ALARM_IN_MEMORY_STATE_CHAR                     '3'
#define APP_ZONE_GET_ALARM_STATE_CHAR								'4'
#define APP_ZONE_GET_BYPASS_STATE_CHAR								'5'
#define APP_ZONE_GET_OPEN_CLOSE_STATE_CHAR							'6'
#define APP_ZONE_GET_TAMPER_STATE_CHAR								'7'
#define APP_ZONE_GET_LOW_SENSITIVITY_STATE_CHAR						'8'
#define APP_ZONE_GET_DELINQUENCY_STATE_CHAR							'9'
#define APP_ZONE_GET_LOWBATT_STATE_CHAR								'A'
#define APP_ZONE_GET_FAULT_STATE_CHAR								'B'
#define APP_ZONE_GET_MASKED_STATE_CHAR                              'C'
#define APP_ZONE_GET_ATTRIBUTES_CHAR								'D'
#define APP_ZONE_WRITE_ZONE_LABEL_CHAR								'E'
#define APP_ZONE_WRITE_ZONE_BYPASS_CHAR								'F'
#define APP_ZONE_GET_ALARM_TYPES_CHAR                               'G'

#define APP_ZONE_ATTRIBUTES_MENU									11
#define APP_ZONE_ATTRIBUTES_REFRESH_CHAR							'0'
#define APP_ZONE_ATTRIBUTES_GET_SYSTEM_INDEX_CHAR					'1'
#define APP_ZONE_ATTRIBUTES_WRITE_CHAR								'2'
#define APP_ZONE_ATTRIBUTES_GET_CHIME_CHAR							'3'
#define APP_ZONE_ATTRIBUTES_GET_BYPASS_CHAR							'4'
#define APP_ZONE_ATTRIBUTES_SET_CHIME_CHAR							'5'
#define APP_ZONE_ATTRIBUTES_SET_BYPASS_CHAR							'6'

#define APP_ACCESSCODE_MENU											12
#define APP_ACCESSCODE_REFRESH_CHAR									'0'
#define APP_ACCESSCODE_GET_VALUE_CHAR								'1'
#define APP_ACCESSCODE_GET_LABEL_CHAR								'2'
#define APP_ACCESSCODE_GET_SYSTEM_INDEX_CHAR						'3'
#define APP_ACCESSCODE_GET_ATTRIBUTES_CHAR							'4'
#define APP_ACCESSCODE_GET_LENGTH_CHAR								'5'
#define APP_ACCESSCODE_WRITE_ACCESS_CODE_LABEL_CHAR					'6'
#define APP_ACCESSCODE_WRITE_ACCESS_CODE_VALUE_CHAR					'7'

#define APP_ACCESSCODE_ATTRIBUTES_MENU								13
#define APP_ACCESSCODE_ATTRIBUTES_REFRESH_CHAR						'0'
#define APP_ACCESSCODE_ATTRIBUTES_GET_SYSTEM_INDEX_CHAR				'1'
#define APP_ACCESSCODE_ATTRIBUTES_WRITE_CHAR                        '2'
#define APP_ACCESSCODE_ATTRIBUTES_GET_CAN_BYPASS_ZONE_CHAR			'3'
#define APP_ACCESSCODE_ATTRIBUTES_GET_REMOTE_ACCESS_CHAR			'4'
#define APP_ACCESSCODE_ATTRIBUTES_GET_ONE_TIME_USE_CHAR				'5'
#define APP_ACCESSCODE_ATTRIBUTES_GET_BELL_SQUAWK_CHAR				'6'
#define APP_ACCESSCODE_ATTRIBUTES_GET_SUPERVISOR_CHAR				'7'
#define APP_ACCESSCODE_ATTRIBUTES_GET_DURESS_CODE_CHAR				'8'
#define APP_ACCESSCODE_ATTRIBUTES_SET_CAN_BYPASS_ZONE_CHAR			'9'
#define APP_ACCESSCODE_ATTRIBUTES_SET_REMOTE_ACCESS_CHAR			'A'
#define APP_ACCESSCODE_ATTRIBUTES_SET_ONE_TIME_USE_CHAR				'B'
#define APP_ACCESSCODE_ATTRIBUTES_SET_BELL_SQUAWK_CHAR				'C'
#define APP_ACCESSCODE_ATTRIBUTES_SET_SUPERVISOR_CHAR				'D'
#define APP_ACCESSCODE_ATTRIBUTES_SET_DURESS_CODE_CHAR				'E'

#define APP_VIRTUAL_KEYPAD_MANAGER_MENU										14
#define APP_VIRTUAL_KEYPAD_MANAGER_REFRESH_CHAR								'0'
#define APP_VIRTUAL_KEYPAD_MANAGER_GET_NUMBER_OF_VIRTUAL_KEYPADS_CHAR		'1'
#define APP_VIRTUAL_KEYPAD_MANAGER_GET_VIRTUAL_KEYPAD						'2'
#define APP_VIRTUAL_KEYPAD_MANAGER_NUMBER_OF_SUPPORTED_VIRTUAL_KEYPADS_CHAR	'3'
#define APP_VIRTUAL_KEYPAD_MANAGER_CREATE_VIRTUAL_KEYPAD_CHAR				'4'
#define APP_VIRTUAL_KEYPAD_MANAGER_DELETE_VIRTUAL_KEYPAD_CHAR               '5'

#define APP_VIRTUAL_KEYPAD_MENU										15
#define APP_VIRTUAL_KEYPAD_CONFIG_CHAR								'C'
#define APP_VIRTUAL_KEYPAD_0_CHAR									'0'
#define APP_VIRTUAL_KEYPAD_1_CHAR									'1'
#define APP_VIRTUAL_KEYPAD_2_CHAR									'2'
#define APP_VIRTUAL_KEYPAD_3_CHAR									'3'
#define APP_VIRTUAL_KEYPAD_4_CHAR									'4'
#define APP_VIRTUAL_KEYPAD_5_CHAR									'5'
#define APP_VIRTUAL_KEYPAD_6_CHAR									'6'
#define APP_VIRTUAL_KEYPAD_7_CHAR									'7'
#define APP_VIRTUAL_KEYPAD_8_CHAR									'8'
#define APP_VIRTUAL_KEYPAD_9_CHAR									'9'
#define APP_VIRTUAL_KEYPAD_STAR_CHAR								'*'
#define APP_VIRTUAL_KEYPAD_POUND_CHAR								'#'
#define APP_VIRTUAL_KEYPAD_ARROWR_CHAR								'>'
#define APP_VIRTUAL_KEYPAD_ARROWL_CHAR								'<'
#define APP_VIRTUAL_KEYPAD_DOUBLE_FIRE_LONG_CHAR                    'F'
#define APP_VIRTUAL_KEYPAD_DOUBLE_AUX_LONG_CHAR                     'A'
#define APP_VIRTUAL_KEYPAD_DOUBLE_PANIC_LONG_CHAR                   'P'
#define APP_VIRTUAL_KEYPAD_GET_SYSTEM_INDEX_CHAR					'G'
#define APP_VIRTUAL_KEYPAD_GET_PARTITION_CHAR                       'H'
#define APP_VIRTUAL_KEYPAD_GET_MODE_CHAR							'I'
#define APP_VIRTUAL_KEYPAD_GET_TYPE_CHAR							'J'
#define APP_VIRTUAL_KEYPAD_GET_WIDTH_CHAR							'K'
#define APP_VIRTUAL_KEYPAD_GET_HEIGHT_CHAR							'L'

#define APP_SPECIFIC_FUNCTIONS_MENU										16
#define APP_SPECIFIC_FUNCTIONS_CHANGE_IAC								'0'
#define APP_SPECIFIC_FUNCTIONS_DEFAULT_IAC								'1'
#define APP_SPECIFIC_FUNCTIONS_READ_LIFESTYLE_NOTIFICATION_SETTINGS		'2'
#define APP_SPECIFIC_FUNCTIONS_WRITE_LIFESTYLE_NOTIFICATION_SETTINGS1	'3'
#define APP_SPECIFIC_FUNCTIONS_WRITE_LIFESTYLE_NOTIFICATION_SETTINGS2	'4'
#define APP_SPECIFIC_FUNCTIONS_DEFAULT_LIFESTYLE_NOTIFICATION_SETTINGS  '5'
#define APP_SPECIFIC_FUNCTIONS_READ_ZONE_NOTIFICATION_SETTINGS			'6'
#define APP_SPECIFIC_FUNCTIONS_WRITE_ZONE_NOTIFICATION_SETTINGS1		'7'
#define APP_SPECIFIC_FUNCTIONS_WRITE_ZONE_NOTIFICATION_SETTINGS2		'8'
#define APP_SPECIFIC_FUNCTIONS_DEFAULT_ZONE_NOTIFICATION_SETTINGS		'9'

#define APP_EXIT_MENU												17

//---------------------------------------------------------------------------
#endif	//_APPLICATION_UI_H_
